<a href="https://colab.research.google.com/github/nounou-mimi/blockchains/blob/main/Hash_function_from_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* It accepts a message  of any length
*  It produces a fixed length message digest
* It is easy (and therefore fast) to compute the message digest for any given message
* The hash is irreversible – it is not possible to generate a message from its m essage digest
*  A small change in a message should generate large changes in the message value
* The hash is collision free, meaning it is not feasible that two different messages would result in the same hash value

In [93]:
import math
def divideString(s, k=8, fill='x'):
    parts_no=math.ceil(len(s)/k)
    result=[]
    for l in range(parts_no):
        s2=s[k*l:k*(l+1)]
        if len(s2)<k:
            to_fill=k-len(s2)
            s2+=fill*to_fill
        result.append(s2)
    return(result)

In [41]:
import numpy as np

In [83]:
import string
import random
# chars=list(string.ascii_lowercase+string.ascii_uppercase)+list(range(10))
# random.shuffle(chars)
# chars

['L',
 'e',
 0,
 'C',
 7,
 'D',
 'o',
 'y',
 'A',
 'Q',
 't',
 'z',
 4,
 'i',
 'd',
 'a',
 'f',
 'q',
 'w',
 'm',
 'c',
 'b',
 'h',
 'Y',
 'x',
 6,
 'l',
 'u',
 5,
 'F',
 'R',
 'M',
 'P',
 2,
 'p',
 'O',
 'U',
 'W',
 'K',
 'E',
 'N',
 'J',
 8,
 'B',
 'V',
 'g',
 'T',
 'Z',
 'n',
 'G',
 's',
 'X',
 'j',
 'H',
 3,
 1,
 9,
 'r',
 'k',
 'S',
 'I',
 'v']

In [84]:
chars=['L',
 'e',
 0,
 'C',
 7,
 'D',
 'o',
 'y',
 'A',
 'Q',
 't',
 'z',
 4,
 'i',
 'd',
 'a',
 'f',
 'q',
 'w',
 'm',
 'c',
 'b',
 'h',
 'Y',
 'x',
 6,
 'l',
 'u',
 5,
 'F',
 'R',
 'M',
 'P',
 2,
 'p',
 'O',
 'U',
 'W',
 'K',
 'E',
 'N',
 'J',
 8,
 'B',
 'V',
 'g',
 'T',
 'Z',
 'n',
 'G',
 's',
 'X',
 'j',
 'H',
 3,
 1,
 9,
 'r',
 'k',
 'S',
 'I',
 'v']

In [94]:
def hash_nour(input):
    parts=divideString(repr(input))
    print(parts)
    coded_parts=[]
    for part in parts:
        coded_part=""
        for i,char in enumerate(part,1):
            char=str((i*ord(char))%127)
            coded_part+=char.zfill(3)
        coded_parts.append(divideString(coded_part,3))
    
    codes=np.asarray(coded_parts)
    codes=codes.astype(int)
    print(codes)
    result=codes.sum(axis=0)%len(chars)
    print(result)
    hash=''.join(map(lambda x:str(chars[x]),result))
    return hash


In [99]:
print(hash_nour("2445"))
hash_nour("2444")

["'2445'xx"]
[[ 39 100  29  81  11 107  78  71]]
[39 38 29 19 11 45 16  9]
EKFmzgfQ
["'2444'xx"]
[[ 39 100  29  81   6 107  78  71]]
[39 38 29 19  6 45 16  9]


'EKFmogfQ'